### ISSUE TITLE
Cannot find module 'snabbdom-to-html' when installing from NPM

### ISSUE THREAD

**Issue by kaosat-dev** [TylorS/cycle-snabbdom#17] opened 2016-02-21 14:43 UTC
Hello !  I am getting the following error when trying to install cycle-snabbdom from NPM : 
`Cannot find module 'snabbdom-to-html' from '/xxxx/cycle-snabbdom/lib`
I am guessing this is the same as #15 reported a while back, but was perhaps not published to npm ? (version numbers match though, so its odd)

**Comment by TylorS** [comment] 2016-02-21 14:54
@acstll This might be of interest to you as well. Seems to be related to updating to snabbdom-to-html 2.1.0

**Comment by TylorS** [comment] 2016-02-21 15:09
@kaosat-dev Could you run `npm ls` and tell me what version of snabbdom-to-html is installed?

**Comment by kaosat-dev** [comment] 2016-02-21 15:48
yes : snabbdom-to-html@2.1.0

**Comment by TylorS** [comment] 2016-02-21 15:50
Could you try explicitly installing `snabbdom-to-html@2.0.1` and reporting back if the error still exists?

**Comment by kaosat-dev** [comment] 2016-02-21 16:33
Tried it, error still stays the same

**Comment by kaosat-dev** [comment] 2016-02-21 16:56
edit: never mind my bad, even with older snabbdom-to-html versions it still fails

**Comment by TylorS** [comment] 2016-02-21 17:34
It's exactly the same error?

Do you mind posting it?

**Comment by kaosat-dev** [comment] 2016-02-21 17:42
exactly the same : Full error message is :

> Error: Cannot find module 'snabbdom-to-html' from '/home/xxx/dev/projects/GreenBotics/automaton/node_modules/cycle-snabbdom/lib'

**Comment by kaosat-dev** [comment] 2016-02-21 17:56
Btw , if you cannot reproduce on your end, perhaps I can try a barebone version to see if it might be my browserify setup ?

**Comment by TylorS** [comment] 2016-02-21 17:59
I can only reproduce with snabbdom-to-html 2.1.0

**Comment by acstll** [comment] 2016-02-21 18:03
@TylorS hey, I will take a look tomorrow morning and make sure 2.1.0 is correctly published and working (I'm away now).

Seems like a problem indeed with my package, I tried it in requirebin.com and got that same error.

Sorry about this!

**Comment by TylorS** [comment] 2016-02-21 18:04
```
~/code/tylors/cycle-snabbdom master*
❯ npm ls | grep snabbdom-to-html
├─┬ snabbdom-to-html@2.1.0

~/code/tylors/cycle-snabbdom master*
❯ npm run dist

> cycle-snabbdom@1.0.3 predist /home/tylor/code/tylors/cycle-snabbdom
> rm -rf dist/ && mkdir dist/


> cycle-snabbdom@1.0.3 dist /home/tylor/code/tylors/cycle-snabbdom
> browserify -t [babelify --global] -t browserify-shim --exclude rx --standalone CycleSnabbdom src/index.js -o dist/cycle-snabbdom.js

Error: Cannot find module 'snabbdom-to-html' from '/home/tylor/code/tylors/cycle-snabbdom/src'
    at /home/tylor/code/tylors/cycle-snabbdom/node_modules/resolve/lib/async.js:46:17
    at process (/home/tylor/code/tylors/cycle-snabbdom/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/tylor/code/tylors/cycle-snabbdom/node_modules/resolve/lib/async.js:188:17)
    at load (/home/tylor/code/tylors/cycle-snabbdom/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/tylor/code/tylors/cycle-snabbdom/node_modules/resolve/lib/async.js:92:31)
    at /home/tylor/code/tylors/cycle-snabbdom/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

```

```
~/code/tylors/cycle-snabbdom master* 9s
❯ npm ls | grep snabbdom-to-html
├─┬ snabbdom-to-html@2.0.1

~/code/tylors/cycle-snabbdom master*
❯ npm run dist

> cycle-snabbdom@1.0.3 predist /home/tylor/code/tylors/cycle-snabbdom
> rm -rf dist/ && mkdir dist/


> cycle-snabbdom@1.0.3 dist /home/tylor/code/tylors/cycle-snabbdom
> browserify -t [babelify --global] -t browserify-shim --exclude rx --standalone CycleSnabbdom src/index.js -o dist/cycle-snabbdom.js


> cycle-snabbdom@1.0.3 postdist /home/tylor/code/tylors/cycle-snabbdom
> uglifyjs dist/cycle-snabbdom.js -o dist/cycle-snabbdom.min.js
```

**Comment by TylorS** [comment] 2016-02-21 18:05
Thank you @acstll. Let me know if there is anything I can do to help?

**Comment by acstll** [comment] 2016-02-21 18:12
2.1.0 is indeed broken, the `lib` folder is missing from the package.

I will publish 2.1.1 and depracate ASAP.

**Comment by TylorS** [comment] 2016-02-21 18:13
:+1:

**Comment by TylorS** [comment] 2016-02-21 18:13
Thank you @acstll

**Comment by acstll** [comment] 2016-02-21 18:51
The main export (`toHMTL`) should work in 2.1.2. But `init` and the `modules` won't. I need to figure out how to set up the `browser` key in `package.json`. I could use some help here :-)

I will release 2.2.0 when it's fully working and deprecate all 2.1.x in npm.

**Comment by TylorS** [comment] 2016-02-21 20:06
@acstll I'll do some reading :+1:

**Comment by kaosat-dev** [comment] 2016-02-21 20:24
thanks a lot for the infos @TylorS  and @acstll !
Let me know if I can also help with something!

**Comment by the-simian** [comment] 2016-02-22 02:08
Ah, looks like I was slow to move. this is the same issue I was experiencing as well, but it was being manifest as a build error.

I wanted to just add that the unit tests in here were passing for me, but the stuff testem kicked off were failing. This was after cloning the repo, while trying to troubleshoot (after experiencing the issue after pulling from npm)

**Comment by TylorS** [comment] 2016-02-22 18:33
This should be fixed with v1.1.0
Please let me know if there are anymore issues.

**Comment by acstll** [comment] 2016-02-22 19:54
I just created an issue to keep track of the bug. I will let you kwow when I figure it out. Thank y'all.

**Comment by kaosat-dev** [comment] 2016-02-23 22:16
@TylorS  it seems to work ok now, thanks !
Should this get closed or remain open for @acstll  updates ?

**Comment by TylorS** [comment] 2016-02-23 22:56
I'll close for now. If for any reason anyone needs to reopen or continue discussing, feel free.

**Closed as completed by TylorS** 2016-02-23 22:56 UTC
